Allow user to define his own backend.
GoogleCloudPlatform/professional-services pull request #517
Opened 2020-07-20 15:40 UTC by Djabx

Here is a proposition so the user can't still define the backend as `StackDriver` and we load the class `StackDriverBackend` in the file `backends/stackdriver.py`

Or now he can define the backend class as: `slo_generator.backends.stackdriver.StackdriverBackend` to define the backend he wants to use.

2020-08-03 09:19 UTC, ocervell commented
@Djabx thanks, really useful ! LGTM if there is no breaking change with the previous code.

2020-08-24 15:35 UTC, ocervell requested changes
A few problems but looks good overall.

2020-08-24 15:35 UTC, ocervell commented on tools/slo-generator/slo_generator/utils.py
> +        klasss_name: the class name to import
typo: 1 's' too much

2020-08-24 15:35 UTC, ocervell commented on tools/slo-generator/slo_generator/utils.py
> +        return import_dynamic(f'slo_generator.exporters.{filename}',
this will work just for exporters, not for backends

2020-09-25 16:12 UTC, ocervell commented
@Djabx , could you open this PR in the new repo https://github.com/google/slo-generator ?
You can checkout your branch and run:
```
git subtree split -P tools/slo-generator -b <NEW_BRANCH>
```
and open a PR from <NEW_BRANCH> to the new repo.

2020-09-26 08:12 UTC, Djabx commented
> @Djabx , could you open this PR in the new repo https://github.com/google/slo-generator ?

Move to: https://github.com/google/slo-generator/pull/34

2020-11-04 22:06 UTC, closed without merging