add dataproc kerberos tf example
GoogleCloudPlatform/professional-services pull request #569
Opened 2020-10-06 19:31 UTC by jaketf

This adds an example terraform module for spinning up a kerberized data lake with cross realm trust.
R: @jhambleton 
CC: @roderickyao

2020-10-06 19:54 UTC, mik-laj commented on examples/kerberized_data_lake/main.tf
> +resource "null_resource" "encrypted_principals" {
Should we add destroyer?

2020-10-06 20:11 UTC, mik-laj commented on examples/kerberized_data_lake/main.tf
> +  users = [
Should these be variables?

2020-10-12 20:30 UTC, jaketf commented on examples/kerberized_data_lake/main.tf
> +resource "null_resource" "encrypted_principals" {
done.

2020-11-05 22:02 UTC, jhambleton requested changes
nice work jake, this looks great! reviewed with minor change requests.

2020-11-06 20:20 UTC, jaketf commented on examples/kerberized_data_lake/main.tf
> +  tenants = [for t in var.tenants : "${t}-svc"]
Hmm I have a different thought. Requiring the user to use `-svc` naming convention is a leaky abstraction.
I think we should have separate vars for users (human) and tenant (non-humans) the `-svc` suffix is assumed for non-human principals by our init actions (implementation detail that should be abstracted away by this  module).

This TF module can enforce this with this line.
I've updated variables to have a separate users input.

2020-11-08 06:41 UTC, jhambleton commented on examples/kerberized_data_lake/main.tf
> +  tenants = [for t in var.tenants : "${t}-svc"]
agree with this update which makes it much cleaner.

2020-11-08 06:46 UTC, jhambleton approved these changes
lgtm

2020-11-08 08:44 UTC, mik-laj approved these changes

2020-11-10 19:27 UTC, merged

2020-11-10 19:31 UTC, mik-laj commented
🎉

2021-01-20 19:04 UTC, mik-laj commented on license-templates/LICENSE.txt
> +Copyright 2020 Google Inc.
This file is not used. Can you say more about it?