Toptalkers
GoogleCloudPlatform/professional-services pull request #641
Opened 2021-04-16 12:01 UTC by lgandras

TopTalkers, comes together with all other VPC FlowLogs tools. Ideally we'd merge this before the 26th of April since there's a blog post coming.

2021-04-16 19:02 UTC, ludoo commented
/gcbrun

2021-04-16 19:06 UTC, ludoo commented
Andras, can you merge `main` again and fix the following lint errors? I'll then review as agreed

```
Step #0 - "lint": 
Step #0 - "lint": In ./tools/vpc-flowlogs-toptalkers/update-ip-range-labels.sh line 5:
Step #0 - "lint": DIR=$(dirname $0)
Step #0 - "lint":               ^-- SC2086: Double quote to prevent globbing and word splitting.
Step #0 - "lint": 
Step #0 - "lint": 
Step #0 - "lint": In ./tools/vpc-flowlogs-toptalkers/update-ip-range-labels.sh line 23:
Step #0 - "lint": source "${DIR}/ip-range-labels/venv/bin/activate"
Step #0 - "lint": ^-- SC1090: Can't follow non-constant source. Use a directive to specify location.
Step #0 - "lint": 
Step #0 - "lint": Some files need to be formatted in ./tools/vpc-flowlogs-toptalkers - FAIL
Step #0 - "lint": ./tools/vpc-flowlogs-toptalkers/update-ip-range-labels.sh 
```

2021-04-17 06:12 UTC, ludoo commented
/gcbrun

2021-04-18 13:52 UTC, lgandras commented
This time I ran `cloud-build-local` (first learned of it :) and the job went through.

2021-04-18 14:07 UTC, ludoo requested changes
A few minor points, looks good otherwise

2021-04-18 14:07 UTC, ludoo commented on tools/vpc-flowlogs-toptalkers/README.md
> +To label the traffic on the specific port add it to the under the `port_labels` key.
"add it under"

2021-04-18 14:07 UTC, ludoo commented on tools/vpc-flowlogs-toptalkers/README.md
> +Once installed with the right configuration values, you'll see several views with the names `top_talkers_report_{current|previous}_month_{daily|weekly|monthly}` under the newly created dataset. This
"for the first entries"

2021-04-18 14:07 UTC, ludoo commented on tools/vpc-flowlogs-toptalkers/ip-range-labels/main.py
> +import json
Can you reorder lexically?

2021-04-18 14:07 UTC, ludoo commented on tools/vpc-flowlogs-toptalkers/ip-range-labels/main.py
> +goog_url="https://www.gstatic.com/ipranges/goog.json"
please put constants in uppercase, and always add spaces around the `=` sign

2021-04-18 14:07 UTC, ludoo commented on tools/vpc-flowlogs-toptalkers/ip-range-labels/main.py
> +goog_url="https://www.gstatic.com/ipranges/goog.json"
please run a linter/formatter or manually add spaces around the `=` sign everywhere, except when passing named function args

2021-04-18 16:12 UTC, ludoo commented
/gcbrun

2021-04-18 16:13 UTC, ludoo approved these changes

2021-04-18 16:15 UTC, ludoo commented
There are still errors in the lint test

```
Step #0 - "lint": Testing formatting for python2 files in ./tools/vpc-flowlogs-toptalkers
Step #0 - "lint": Testing formatting for python3 files in ./tools/vpc-flowlogs-toptalkers
Step #0 - "lint": make: *** [Makefile:28: test] Error 1
Step #0 - "lint": Some files need to be formatted in ./tools/vpc-flowlogs-toptalkers - FAIL
Step #0 - "lint": ./tools/vpc-flowlogs-toptalkers/ip-range-labels/main.py
```

2021-04-18 18:22 UTC, ludoo commented
/gcbrun

2021-04-18 18:45 UTC, merged