OpenAPI to Cloud Armor
GoogleCloudPlatform/professional-services pull request #743
Opened 2021-12-22 10:17 UTC by cgrotz

Simple tool that generates Cloud Armor rules from an OpenAPI specification

2021-12-22 12:14 UTC, boredabdel commented
/gcbrun

2021-12-23 09:42 UTC, boredabdel requested changes
One comment, the rest looks good

2021-12-23 09:42 UTC, boredabdel commented on tools/openapi-to-cloud-armor/README.md
> +The resulting yaml can be loaded into CloudRun using
You mean Cloud Armor ?

2021-12-23 12:56 UTC, cgrotz commented on tools/openapi-to-cloud-armor/README.md
> +The resulting yaml can be loaded into CloudRun using
yes, oh man 🤣

2021-12-23 12:58 UTC, cgrotz commented
@boredabdel thanks, I fixed the typo, sorry about that.

2021-12-23 15:45 UTC, boredabdel commented
/gcbrun

2022-01-04 10:29 UTC, boredabdel approved these changes
LGTM

2022-01-04 10:29 UTC, merged